### PR TITLE
fix: UI changes 

### PR DESCRIPTION
**Pull request by harshitprg**
### **fix: UI changes**
1. Fixed the UI design with CSS and Bootstrap Frameworks
2. The updated UI provides a more intuitive and user-friendly experience.
3. Responsive UI
 Screenshot 2023-11-21 195031

### CODE REVIEW

**Comment by agamswaroop619** [comment]
#1

**Comment by agamswaroop619** [comment]
@harshitprg Please add description of what you have done here as well.

**Comment by agamswaroop619** [comment]
#1

**Comment by harshitprg** [comment]
> @harshitprg Please add description of what you have done here as well.

#1

**Comment by agamswaroop619** [comment]
Thanks for for your contribution @harshitprg .
Looking forward to future collaborations as well !

**Pull request merged**
